version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret

volumes:
  db-data:
    driver: local
