version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      PORT: 5000
    env_file:
      - ./.env

volumes:
  db-data:
    driver: local
