name: continuous-integration
on: [push]
env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-linux:
    runs-on: ubuntu-20.04 # won't work on earlier version, because dependencies are too old there
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Update Submodules
      run: |
        git submodule update --init deps/glwrap deps/gltf deps/sol2 deps/imgui deps/soloud/repo
        cd deps/glwrap && git submodule update --init deps/stb && cd ../..
        cd deps/gltf && git submodule update --init simdjson
    - name: Update Apt
      run: sudo apt update
    - name: Install Dependencies
      run: |
        sudo apt install --assume-yes build-essential ninja-build cmake clang-10 libsdl2-dev libfmt-dev libglm-dev libenet-dev libdocopt-dev libluajit-5.1-dev
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_CXX_COMPILER=clang++-10 ..
    - name: Build
      run: cmake --build build --parallel
  build-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Update Submodules
      run: |
        git submodule update --init .\deps\glwrap .\deps\gltf .\deps\sol2 .\deps\imgui .\deps\soloud\repo
        cd .\deps\gltf
        git submodule update --init .\simdjson
    - name: Install Dependencies
      run: |
        git submodule update --init .\vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install --triplet x64-windows sdl2 fmt glm stb enet docopt luajit
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE:STRING=Release ..
    - name: Build
      run: cmake --build build --config Release --parallel
    - name: Assemble Artifact Directory
      shell: bash
      run: |
        mkdir -p "artifact-out/ARBITRARY COMPLEXITY"
        cd "artifact-out/ARBITRARY COMPLEXITY"
        cp ../../build/Release/complexity.exe .
        cp ../../build/Release/*.dll .
        mkdir media
        cp ../../media/*.glb media/
        cp ../../media/*.ttf media/
        cp -R ../../media/sounds media/sounds
        cp -R ../../media/systems media/systems
        cp -R ../../media/skybox media/skybox
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ARBITRARY_COMPLEXITY-win64
        path: artifact-out
